### ISSUE TITLE
Sdoapi and sdoutil are missing

### ISSUE THREAD

**Issue by jlstanus** [talend-spatial/talend-spatial#73]
Hello,

Sdoapi and sdoutil are missing when i want to use oracle spatial input to a shapefile ?
I cannot download them. Downland and install button is greyed
Where can i find this jar or can you share them?

Thanks

Talend-spatial looks dead (so which open ETL do i have to use?)

**Comment by fxprunayre** [comment]
> Sdoapi and sdoutil are missing when i want to use oracle spatial input to a shapefile ?

This may help https://www.talendforge.org/forum/viewtopic.php?id=31996. Your issue sounds related to an Oracle licencing thing.




> Talend-spatial looks dead (so which open ETL do i have to use?)

AFAIK, it's still working fine with latest Talend Studio and indeed, there is no major new feature in progress, but not a reason to say "dead".

**Comment by jlstanus** [comment]
OK, thanks for your answer.

But the guy has got the 2 libraries but doesn't say where. I have not this libraries. Where can i get them (from a safe place, not jardownload.com by example)

I w'd not offend you by saying "dead" but the last update was last year i think. Thanks for all the work you accomplished. 
By the way, i've seen this: http://www.disy.net/fileadmin/common/dokumente/downloads/produktblaetter/Disy_Geospatial_Integration_Talend_2017_web-english.pdf
