### ISSUE TITLE
Talend-Spatial with Talend-7.2.1

### ISSUE THREAD

**Issue by edwinalex035** [talend-spatial/talend-spatial#79]
Hi all,

I'm starting working with Talend and I need to use some spatial component and I found this project which will allow me to do several staff. I downloaded Talend-7.2.1 and copy the plugins folder of this project but the components are not recognize into Talend. Could you help me indicate if a miss any steps. I follow the installation steps.

Regards,

**Comment by maharogun** [comment]
i see same err, too. T-T

**Comment by archaeogeek** [comment]
I believe that you need to match versions of Talend and Talend-Spatial. 7.1 works fine (but I experienced the same problem trying to use Talend-Spatial 7.1 in Talend 7.2 and 7.3)

**Comment by fxprunayre** [comment]
Same as #80
