### ISSUE TITLE
Talend Spatial 7.1 - sOGRInfoInput - nb_faetures incorrect datatype int instead of long

### ISSUE THREAD

**Issue by lucvanlinden** [talend-spatial/talend-spatial#81]
Talend 7.1 + SDI 7.1
component sOGRINfoinput
nb_faetures cause an casting error cannot cast from Long to int.
at: nbFeatures_<%=cid %> = poLayer_<%=cid %>.GetFeatureCount();

had to change the _java.xml file 
                <COLUMN NAME="nb_features" TYPE="id_Long" LENGTH="10" />
TYPE=id_Long (instead of id_Integer)

AND _begin.javajet
long nbFeatures_<%=cid %> = 0;

Not sure if this is the appropriate change but at least it resolved to issue.
Not sure if this relates also to the version of OGR as such.

**Comment by fxprunayre** [comment]
I confirm the error once running with GDAL 3.0.4 (and Talend 7.3.1).

**Comment by fxprunayre** [comment]
Thanks for the fix. I update `gdal.jar` to 3.0.4. So the next version will depend on it.
