### ISSUE TITLE
Where is Talend Spatial 7.3.1?

### ISSUE THREAD

**Issue by Cris70** [talend-spatial/talend-spatial#88]
Hi,
in page https://github.com/talend-spatial/talend-spatial/blob/7.3/INSTALL.md I see "Talend spatial module version 7.3.1" mentioned in "List of changes" section.
However, there is no v7.3.1 available on Sourceforge.
Where can I find it? Release 7.1.1 is not working in TOS 7.3.1.

Thank you in advance
Cris

**Comment by archaeogeek** [comment]
I can confirm that upgrading everything to version 7.4.1 works, if that helps?

**Comment by fxprunayre** [comment]
7.3.1 was not released. 7.4.1 is the latest. Download from https://sourceforge.net/projects/sdispatialetl/files/sdispatialetl/
