### ISSUE TITLE
Questions regarding functionality?

### ISSUE THREAD

**Issue by nagyrobir** [talend-spatial/talend-spatial#91]
Hi!

I have installed TOS DI 7.4.1 with TOS Geospatial 7.4.1 everything is working ok. I wanted to ask, is there any kind of support for operations like: Intersects, Within, Dwithin, to see how certain geometries overlap?

I don't see a lot of functions here, or have i done something wrong?
![image](https://user-images.githubusercontent.com/46939331/178228384-4bf469f3-0a12-4d27-9ae1-d3ccca983f78.png)

**Comment by fxprunayre** [comment]
Check the demo workspace, you can use routines in tMap to make spatial join https://github.com/talend-spatial/workspace-demo-spatial/tree/6.x/DEMO-SPATIAL/process/Spatial/test_vector/Routines

**Comment by nagyrobir** [comment]
Thank you again for the pointers!
