### ISSUE TITLE
Using posgres to leverage postgis syntax before extracting in Talend

### ISSUE THREAD

**Issue by nagyrobir** [talend-spatial/talend-spatial#92]
Is there any way i could use tpostgresqlinput or similar to parse an SQL query with postgis script in it?

Let's say i have a point table called POI and  i would like to extract a buffered version of it.

Select st_buffer(geom,1)  as geom from POI
 Is it possible?

I tried in a way to do it, but i get an error that "Geometry cannot be resolved to a type".

**Comment by fxprunayre** [comment]
As tpostgresqlinput has no dependency on the spatial module, you need to add a component in your job which will load the spatial module dependency. Then it should work. Check the demo workspace with https://github.com/talend-spatial/workspace-demo-spatial/blob/6.x/DEMO-SPATIAL/process/Spatial/test_vector/IO/test_PostGis_0.1.item

**Comment by nagyrobir** [comment]
Thank's for the answers Francois. I am super hyped that i got this working!
