### ISSUE TITLE
Duplicate local variable ogrGeometry_sOgrInput_1 error in 7.4

### ISSUE THREAD

**Issue by archaeogeek** [talend-spatial/talend-spatial#93]
I'm using version 7.4, and trying to iterate through the tables in a file geodatabase (with the eventual aim of producing metadata for each table rather than for the whole geodatabase). I have an sOGRInput component, which returns the expected results if used on its own, but if I try to log the output using tLogRow or tFlowToIterate then I get the above error. I can see that this seems like the same issue as in https://github.com/talend-spatial/talend-spatial/issues/63 but I can confirm I have that fix in place.

**Comment by fxprunayre** [comment]
Can you share a screenshot of your job ?

**Comment by archaeogeek** [comment]
@fxprunayre not sure if this is enough information for you:
![Screenshot from 2022-08-01 16-57-12](https://user-images.githubusercontent.com/1544849/182190351-f9dc8ccf-9d12-4dbd-aac7-54fbf892856d.png)

**Comment by archaeogeek** [comment]
This can be closed. I had copied the tLogRow and tFlowToIterate components from a different job. If I use new components then it works (even though the other job works fine too)
